name: 🏷️ - Publish WordPress Theme to GitHub

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (if your theme uses Node.js tools, e.g., for build processes)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Install dependencies and build the theme (if applicable)
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build theme (if applicable)
        run: npm run production

      # Create a zip archive of the theme for distribution
      - name: Create a zip file of the theme
        run: npm run zip

      # Rename the zip file to include the tag name
      - name: Rename zip file
        run: |
          tag_name=${{ github.ref_name }}
          mv git-blog-theme.zip git-blog-theme-${tag_name}.zip

      # Upload the renamed zip file as a release asset if a tag is pushed
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: git-blog-theme-${{ github.ref_name }}.zip
          generate_release_notes: true
          discussion_category_name: Announcements
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
